version: "3.9"

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  back:
    build: ./dzen-back
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - URL_REDIS=redis://redis:6379
      - URL_FRONT=${URL_FRONT}
    volumes:
      - back_data:/upload

  front:
    build: ./dzen-front
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}

volumes:
  postgres_data:
  redis_data:
  back_data:
